### ISSUE TITLE
[docs] Broken Links

### ISSUE THREAD

**Issue by svx** [testthedocs/rakpart#58]
**Describe the bug**

ttd-linkcheck reports broken links in the docs of ttd-vale.
![broken-links-rakpart](https://user-images.githubusercontent.com/358860/48706332-364b7180-ebfc-11e8-9eee-972c01386811.png)

**To Reproduce**

-  Run: `make check-links`

**Expected behavior**

Have no broken links

**Screenshots**

See above

**Comment by ChrisChinchilla** [comment]
@svx Yeah, these have all moved now after big changes from Vale. I need to do an overarching docs update now anyway after all the changes I needed in Vale are complete, so will fix this when I do that.
